#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyufusingsum90.090000
#SBATCH -o nyufusingsum90.090000.o%j
#SBATCH -e nyufusingsum90.090000.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem=64380
#SBATCH -p gpu

module add python/2.7-gcc
source ~/env/bin/activate
module list

hostname
mpdboot
python ~/hand_pose_estimation/training_script.py 5 fusing 0.090000 9 sum --predef_hp --validate --save_model --save_loss --early_stopping --shuffle --weights_dir /home/mvrigkas/hand_pose_estimation/models/NYU/fusing/sum/9/0.090000/weights.npz
mpdallexit
deactivate