#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyufusingmax2
#SBATCH -o nyufusingmax2.o%j
#SBATCH -e nyufusingmax2.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem 23999
#SBATCH -p gpu

module add python/2.7-gcc
source ~/python_apps/env/bin/activate
module list

hostname
mpdboot
python ~/lasagne/hand_pose_estimation/training_script.py 5 fusing 2 max --predef_hp --validate --save_model  --save_loss --early_stopping --shuffle
mpdallexit
deactivate
