#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyusimplergbd0.080000
#SBATCH -o nyusimplergbd0.080000.o%j
#SBATCH -e nyusimplergbd0.080000.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem=64380
#SBATCH -p gpu

module add python/2.7-gcc
source ~/python_apps/env/bin/activate
module list

hostname
mpdboot
python ~/lasagne/hand_pose_estimation/training_script.py 5 simple 0.080000   --predef_hp --validate --save_model  --save_loss --early_stopping --shuffle
mpdallexit
deactivate