#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyuscore_fusing0.070000
#SBATCH -o nyuscore_fusing0.070000.o%j
#SBATCH -e nyuscore_fusing0.070000.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem=64380
#SBATCH -p gpu

module add python/2.7-gcc
source ~/python_apps/env/bin/activate
module list

hostname
mpdboot
python ~/lasagne/hand_pose_estimation/training_script.py 5 score_fusing 0.070000   --predef_hp --validate --save_model   --early_stopping --shuffle --weights_dir /home/ekazakos/lasagne/hand_pose_estimation/models/NYU/score_fusing/0.070000/weights.npz
mpdallexit
deactivate
