#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyufusingconcat70.120000
#SBATCH -o nyufusingconcat70.120000.o%j
#SBATCH -e nyufusingconcat70.120000.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem=64380
#SBATCH -p gpu

module add python/2.7-gcc
source ~/env/bin/activate
module add cuda-toolkit/7.5-cudnn-5.1
module list

hostname
mpdboot
python ~/hand_pose_estimation/training_script.py 5 fusing 0.120000 7 concat --predef_hp --validate --save_model --save_loss --early_stopping --shuffle 
mpdallexit
deactivate