#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyuscore_fusingsum0.020000
#SBATCH -o nyuscore_fusingsum0.020000.o%j
#SBATCH -e nyuscore_fusingsum0.020000.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem=64380
#SBATCH -p gpu

module add python/2.7-gcc
source ~/env/bin/activate
module add cuda-toolkit/7.5-cudnn-5.1
module list

hostname
mpdboot
python ~/hand_pose_estimation/training_script.py 5 score_fusing 0.020000 0 sum --predef_hp --validate --save_model --save_loss --early_stopping --shuffle --weights_dir models/NYU/score_fusing/sum/0.020000/weights.npz
mpdallexit
deactivate