#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyusimplergb0.030000
#SBATCH -o nyusimplergb0.030000.o%j
#SBATCH -e nyusimplergb0.030000.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem=64380
#SBATCH -p gpu

module add python/2.7-gcc
source ~/env/bin/activate
module add cuda-toolkit/7.5-cudnn-5.1
module list

hostname
mpdboot
python ~/hand_pose_estimation/training_script.py 4 simple 0.030000 0 concatconv --predef_hp --validate --save_model --save_loss --early_stopping --shuffle 
mpdallexit
deactivate