#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyufusingmax70.110000
#SBATCH -o nyufusingmax70.110000.o%j
#SBATCH -e nyufusingmax70.110000.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem=64380
#SBATCH -p gpu

module add python/2.7-gcc
source ~/env/bin/activate
module add cuda-toolkit/7.5-cudnn-5.1
module list

hostname
mpdboot
python ~/hand_pose_estimation/training_script.py 5 fusing 0.110000 7 max --predef_hp --validate --save_model --save_loss --early_stopping --shuffle 
mpdallexit
deactivate