#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 -n 20
#SBATCH -J nyufusingsum20.070000
#SBATCH -o nyufusingsum20.070000.o%j
#SBATCH -e nyufusingsum20.070000.err%j
#SBATCH --mail-user=kazakosv90@gmail.com
#SBATCH --mail-type=all
#SBATCH --mem=64380
#SBATCH -p gpu

module add python/2.7-gcc
source ~/python_apps/env/bin/activate
module list

hostname
mpdboot
python ~/lasagne/hand_pose_estimation/training_script.py 5 fusing 0.070000 2 sum --predef_hp --validate --save_model  --save_loss --early_stopping --shuffle 
mpdallexit
deactivate